### ISSUE TITLE
cross-compile moonfire for arm linux

### ISSUE THREAD

**Issue by brian-liu1** [scottlamb/moonfire-nvr#135]
Does this project support arm linux? or are there some doc for build for arm linux

**Comment by scottlamb** [comment]
Yes, it does. The Docker container is prebuilt for arm (both 32-bit and 64-bit), and the Docker build instructions describe cross-compiling to arm. There are no instructions from cross-compiling without Docker because it can be painful to get the right compiler/linker/native libraries in place (particularly if you're not using the same distribution on both systems), but if you're determined enough you might be able to figure it out by examining the docker setup.
