### ISSUE TITLE
Arlo?

### ISSUE THREAD

**Issue by tagyoureit** [scottlamb/moonfire-nvr#14]
Could Moonfire support Arlo?  Putting aside any debates about the usefulness of non-full-time streaming, it looks like others have decoded [RTSP streams in Arlo](https://github.com/jeffreydwalter/arlo).  Could Moonfire record the Arlo streams?

**Comment by scottlamb** [comment]
From looking at Arlo.StartStream, it looks like rather than having a fixed RTSP URL, Arlo does a HTTP handshake to get a temporary RTSP URL. That seems possible to do. I don't have an Arlo, though. I'd welcome PRs from someone who does. :)

**Comment by scottlamb** [comment]
One other note: it looks like the handshake URL is a centralized thing on the public Internet, rather than directly connecting to the camera over the Internet or LAN. I'm unsure from looking at that if the returned RTSP works this way, too. Keep in mind that Moonfire NVR continuously streams; if you're running it locally, it'd be a shame if everything got sent to some central Arlo server and then back. It wouldn't work when your ISP cuts out, there'd be a limit on number of cameras you can support at full resolution, and it'd limit your bandwidth available for other things.

I don't know anything about Arlo, but if there's another way of initiating a direct RTSP session without involving a central server at all, that'd likely be preferable.

**Comment by tagyoureit** [comment]
Thanks, I don't know much about RTSP, (or GO! for that matter), so might try to see if I can get something working, but this might be a tall mountain for me to climb.

**Comment by scottlamb** [comment]
I don't think we'll ever support Arlo, because Arlo still doesn't support local RTSP. https://community.arlo.com/t5/Arlo-Idea-Exchange/Allow-access-to-RTSP/idc-p/1773144
