### ISSUE TITLE
Upgrade on 12/23/2022: 16 vulnerabilities in Node

### ISSUE THREAD

**Issue by jlpoolen** [scottlamb/moonfire-nvr#251]
**Describe the bug**
During upgrade, 16 vulnerabilities are mentioned:
```
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ npm install

up to date, audited 1808 packages in 14s

209 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (1 low, 11 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ 

```
What should I do?

**To Reproduce**
   cd [to project directory]
   git pull
   cd server
   cargo build --release
   sudo install -m 755 target/release/moonfire-nvr /usr/local/bin
   cd ..
   cd ui
   npm install
   npm run build

**Expected behavior**
No warnings.

**Screenshots**
![putty_2022-12-23_13-17-32](https://user-images.githubusercontent.com/227313/209406441-9f35377a-278b-410f-9aa6-00398f89d10f.png)

**Server (please complete the following information):**
Raspberry Pi4
```
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ uname -a
Linux pi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $
```

```
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ git describe --dirty
v0.7.4-3-gfd7438d-dirty
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ moonfire-nvr --version
moonfire-nvr 0.7.4
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $ date
Fri 23 Dec 2022 01:22:43 PM PST
jlpoole@pi:/usr/local/src/moonfire-nvr/ui $

```

**Additional context**
I do not follow a regular upgrade procedure for the Raspberry Pi.  Should I?  If so, can you provide a recipe of commands I should use?

**Comment by scottlamb** [comment]
I'm on my phone, but the short version is that node security warnings are notorious for being false positives. They're things like DoS potential in a tool used during the build process, where someone who controls the input can run arbitrary code anyway by design. They are also quite hard to get rid of because there's often no api-compatible fixed version, so when some dependency of a dependency requires a certain version it's more work than it's worth to change that. I don't have the time for it.
