### ISSUE TITLE
how to update ui(user interfacce) content ,and package ..

### ISSUE THREAD

**Issue by maomj200811** [scottlamb/moonfire-nvr#305]
**Describe the bug**
A clear and concise description of the problem.

**I need modify ui text and how to  rebuild it .**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
  - `moonfire-nvr --version`
  - Attach a [log file](https://github.com/scottlamb/moonfire-nvr/blob/master/guide/troubleshooting.md#viewing-moonfire-nvrs-logs). Run with the `RUST_BACKTRACE=1` environment variable set if possible.

**Camera (please complete the following information):**
  - Camera manufacturer and model: [e.g. Reolink RLC-410]
  - Firmware version: [e.g. `V2.0.0.1215_16091800`]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maomj200811** [comment]
I use the newest version 0.7.12 now ,server and ui is one package, I can not update ui module only?

**Comment by scottlamb** [comment]
> I use the newest version 0.7.12 now ,server and ui is one package, I can not update ui module only?

You can, by overriding `uiDir` in the config, see [here](https://github.com/scottlamb/moonfire-nvr/blob/master/ref/config.md#reference). (The "Defaults to `/usr/local/lib/moonfire-nvr/ui`" written there is incomplete/wrong. I'll fix it. On a release binary, the default is actually `uiDir = { bundled = true }` which means to use the UI that's bundled inside the binary.)

...but I'm wondering why:

* If you're hoping to work on UI development, thank you, and [this guide](https://github.com/scottlamb/moonfire-nvr/blob/master/guide/developing-ui.md) might be more helpful. It has instructions for setting up a proxy server that provides a more pleasant development experience via hot reloading.
* Otherwise, could you help me understand what you're trying to do?
